### ISSUE TITLE
Support long-format volumes

### ISSUE THREAD

**Issue by jvansanten** [AmpelProject/singularity-stack#3]
e.g. 
```    
volumes:
      - type: tmpfs
        target: /opt/conda/pkgs
      - type: volume
        target: /opt/conda/envs
        source: envs
      - ..:/Ampel
      - ./ampel-start.sh:/ampel-start.sh
```

Probably need to alias `volume` type to `bind`, and warn about limits on `tmpfs` sizes.
