### ISSUE TITLE
Support replica count in deploy block

### ISSUE THREAD

**Issue by jvansanten** [AmpelProject/singularity-stack#6]
e.g.
```
version: '3'
services:
  redis:
    image: redis:alpine
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
```

This probably requires the nanny processes to communicate back to a central instance that their process has exited.
